// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Replay(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Replay'](arg1, arg2, arg3, arg4);
}

export function ReplayPayload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplayPayload'](arg1, arg2, arg3, arg4);
}

export function StartProxy(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3, arg4);
}
