// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Replay(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ReplayPayload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartProxy(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;
